# Generated by Django 4.2.14 on 2024-08-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.TextField(default=''),
        ),
    ]
