# Generated by Django 4.2.14 on 2024-08-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser_city_customuser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='latitude',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='longitude',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.IntegerField(default=0),
        ),
    ]
